---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: eureka-ing
  labels:
    ing: eureka
spec:
  rules:
  - host: www.eureka1.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: eureka-svc
            port:
              number: 8040
  tls:
  - hosts:
    - www.eureka1.com    
    secretName: tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
  labels:
    name: eureka-svc
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
  - name: http
    port: 8040
    targetPort: 8040
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  labels:
    deploy: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      name: eureka
      labels:
        app: eureka
    spec:
      imagePullSecrets: 
      - name: myregistery
      containers:
      - name: eureka
        image: registry.cn-hangzhou.aliyuncs.com/kxq/eureka:ed586c0e
        imagePullPolicy: Always
        env:
        - name: eureka
        ports:
        - name: http
          containerPort: 8040
