apiVersion: v1
kind: Pod
metadata:
  name: secret-voume
  labels:
    name: secret
spec:
  containers:
    - name: secretdb
      image: nginx
      volumeMounts:
        - name: secret-v
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secret-v
      secret:
        secretName: mysecret
