apiVersion: v1
kind: Pod
metadata:
 name: dapi-test-pod
spec:
 containers:
 - name: test-config
   image: nginx
   command: ["/bin/bash","-c","env"]
   env:
    - name: SPECIAL_LEVE_KEY
      valueFrom:
        configMapKeyRef:
         name: special-config
         key: special.how
    - name: SPECIAL_TYPE_KEY
      valueFrom:
        configMapKeyRef:
         name: special-config
         key: special.type
   envFrom:
     - configMapRef:
        name: env-config #configmap来源
 restartPolicy: Never
