apiVersion: v1
kind: Pod
metadata:
 name: dapi-test-pod1
spec:
 containers:
 - name: test-config1
   image: nginx
   command: ["/bin/bash","-c","echo $(SPECIAL_LEVE_KEY) $(SPECIAL_TYPE_KEY)"]
   env:
    - name: SPECIAL_LEVE_KEY
      valueFrom:
        configMapKeyRef:
         name: special-config
         key: special.how
    - name: SPECIAL_TYPE_KEY
      valueFrom:
        configMapKeyRef:
         name: special-config
         key: special.type
   envFrom:
     - configMapRef:
        name: env-config
 restartPolicy: Never
